import pytest
import asyncio
import json
from collections import deque
from unittest.mock import AsyncMock, patch
from typing import Literal

from src.ws_liquidation import (
    bybit_ws_consumer, binance_ws_consumer,
    parse_bybit_msg, normalize_bybit_event,
    normalize_binance_event,
    LiquidationEvent
)
from src.config import Config

# Mock websockets.connect for testing
@pytest.fixture
def mock_websocket_connect():
    with patch('websockets.connect') as mock_connect:
        mock_ws = AsyncMock()
        mock_ws.recv.side_effect = [
            json.dumps({"topic": "liquidation.SOLUSDT", "data": {"s": "SOLUSDT", "p": "100.0", "lq": "1.0", "S": "Buy", "T": 1678886400000, "o": "order1"}}),
            json.dumps({"e": "forceOrder", "o": {"s": "SOLUSDT", "ap": "100.1", "q": "1.1", "S": "SELL", "E": 1678886401000, "i": "order_binance1"}}),
            # Simulate a duplicate Bybit event
            json.dumps({"topic": "liquidation.SOLUSDT", "data": {"s": "SOLUSDT", "p": "100.0", "lq": "1.0", "S": "Buy", "T": 1678886400000, "o": "order1"}}),
            # Simulate a non-matching Binance event
            json.dumps({"e": "forceOrder", "o": {"s": "BTCUSDT", "ap": "20000.0", "q": "0.1", "S": "SELL", "E": 1678886402000, "i": "order_binance2"}}),
            asyncio.CancelledError # To stop the consumer loop
        ]
        mock_connect.return_value.__aenter__.return_value = mock_ws
        yield mock_connect

def test_parse_bybit_msg():
    msg = json.dumps({"topic": "liquidation.SOLUSDT", "data": {"s": "SOLUSDT", "p": "100.0", "lq": "1.0", "S": "Buy", "T": 1678886400000, "o": "order1"}})
    parsed = parse_bybit_msg(msg)
    assert parsed["data"]["s"] == "SOLUSDT"

def test_normalize_bybit_event():
    # v5 format: data is an ARRAY of events with different field names
    event_data = {"topic": "allLiquidation.SOLUSDT", "data": [{"T": 1678886400000, "s": "SOLUSDT", "S": "Buy", "v": "1.0", "p": "100.0"}]}
    events = normalize_bybit_event(event_data)
    assert len(events) == 1
    assert events[0].exchange == "bybit"
    assert events[0].symbol == "SOL/USDT"
    assert events[0].side == "LONG"
    assert events[0].price == 100.0
    assert events[0].qty == 1.0

def test_normalize_binance_event():
    event_data = {"e": "forceOrder", "o": {"s": "SOLUSDT", "ap": "100.1", "q": "1.1", "S": "SELL", "E": 1678886401000, "i": "order_binance1"}}
    normalized = normalize_binance_event(event_data)
    assert normalized is not None
    assert normalized.exchange == "binance"
    assert normalized.symbol == "SOL/USDT"
    assert normalized.side == "SHORT" # Corrected: "SELL" in Binance means short liquidation
    assert normalized.price == 100.1
    assert normalized.qty == 1.1
    assert normalized.qty_usdt == pytest.approx(110.11) # 100.1 * 1.1
    assert normalized.order_id == "1678886401000-SOL/USDT-SHORT-100.1" # Pseudo-ID generated by normalize_binance_event
